CREATE TABLE products (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  image TEXT,
  price TEXT,
  brand TEXT,
  size TEXT,
  description TEXT,
  date_created TIMESTAMPTZ NOT NULL DEFAULT now()
);